version: '3'

services:
  backend:
    restart: always
    build: ./backend
    ports:
      - 8000:8080
    command: npm run dev
    volumes:
      - ./backend/src/:/app/src
      - data_backend_libs:/app/node_modules
    env_file: .env
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.7
    volumes:
      - ./db_data:/data/db
    env_file: .env

  frontend:
    restart: always
    build: ./frontend
    ports:
      - 8080:8080
    command: npm run dev
    volumes:
      - ./frontend:/app
      - data_frontend_libs:/app/node_modules
    env_file: .env

volumes:
  data_frontend_libs:
    driver: local
  data_backend_libs:
    driver: local
