- name: setup environment variables
  become: true
  become_user: "{{ dh_username }}"
  shell: cp {{ dh_projects_root_path }}/.env {{ dh_current_release_path }}/.env

- name: Pull Images
  become: true
  become_user: "{{ dh_username }}"
  shell: |
    cd {{ dh_current_release_path }}/deployment/production/backend && \
    docker-compose -f ./docker-compose-up.yaml pull

- name: Restart
  become: true
  become_user: "{{ dh_username }}"
  shell: |
    cd {{ dh_current_release_path }}/deployment/production/backend && \
    docker-compose -f ./docker-compose-up.yaml down && \
    docker-compose -f ./docker-compose-up.yaml up

- debug: msg={{ ps.stdout }}
