- name: setup environment variables
  become: true
  become_user: "{{ dh_username }}"
  register: ps
  shell: cp {{ dh_projects_root_path }}/.env {{ dh_current_release_path }}/.env

- name: Pull Images
  become: true
  become_user: "{{ dh_username }}"
  register: ps
  shell: |
    cd {{ dh_current_release_path }}/deployment/production/backend && \
    export $(cat {{ dh_current_release_path }}/.env | xargs) && \
    echo $CR_PASSWORD | docker login ghcr.io -u $CR_USERNAME --password-stdin && \
    docker compose -f ./docker-compose-up.yaml pull

- name: Restart
  become: true
  become_user: "{{ dh_username }}"
  register: ps
  shell: |
    cd {{ dh_current_release_path }}/deployment/production/backend && \
    export $(cat {{ dh_current_release_path }}/.env | xargs) && \
    docker compose -f ./docker-compose-up.yaml down && \
    docker compose -f ./docker-compose-up.yaml up -d && \
    docker compose -f ./docker-compose-up.yaml logs backend

- debug: msg={{ ps.stdout }}
