version: '3'

services:
  frontend:
    restart: always
    image: ${CR_BASE}/delivery-help-frontend-staging:latest
    env_file: ${HOME}/projects/.env
    ports:
      - 80:80

  backend:
    restart: always
    image: ${CR_BASE}/delivery-help-backend-staging:latest
    env_file: ${HOME}/projects/.env
