version: '3'

services:
  frontend:
    restart: always
    image: ${CR_BASE}/delivery-help-frontend-staging:latest
    command: nginx -g "daemon off";
    env_file: ${HOME}/projects/.env
    ports:
      - 80:80

  backend:
    restart: always
    image: ${CR_BASE}/delivery-help-backend-staging:latest
    command: npm run start
    env_file: ${HOME}/projects/.env
