version: '3'

services:
  frontend:
    image: ${CR_BASE}/delivery-help-frontend-staging:latest
    build:
      context: ../..
      dockerfile: ./deployment/staging/frontend/Dockerfile

  backend:
    image: ${CR_BASE}/delivery-help-backend-staging:latest
    build:
      context: ../..
      dockerfile: ./deployment/staging/backend/Dockerfile
